//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeleCshapG4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Releves
    {
        public int id_releve { get; set; }
        public System.DateTime releve_DTTM { get; set; }
        public decimal hygrometrie { get; set; }
        public decimal temperature { get; set; }
        public int id_capteur { get; set; }
        public System.DateTime insertion_DTTM { get; set; }
    
        public virtual Capteurs Capteurs { get; set; }
    }
}
